### PR TITLE
fix 'ascii' codec can't decode byte 0xef in position 583: ordinal not…

### PR DESCRIPTION
**Pull request by mojgans**
… in range(128)

we had multiple errors like: 
Unicodedecodeerror ascii codec can t decode byte 0xe3 in position 0 ordinal not in range 128 
or
CRITICAL: 'ascii' codec can't decode byte 0xef in position 583: ordinal not in range(128) 
setting utf-8 as default fixed the failure

### CODE REVIEW

**Comment by mojgans** [comment]
the fix is mainly to set utf-8 as default fix. There were cases where we were seeing the error mentioned above and after I applied this change it is fixed. I have this in our environment for over 4 month and have not hit this error anymore.

**Comment by chipx86** [comment]
Not sure why the entire file is being replaced, but that's a bit of a red flag for me.

We don't accept pull requests. This will need to be posted to https://reviews.reviewboard.org/, along with detailed info on the fix, and unit tests demonstrating the fix solves the core problem.

Thanks!

**Comment by mojgans** [comment]
Is there any instruction on how to submit this. there is another fix that I have for Clearcase. What kind of proof also required. This has been working just fine with over 160 developer using these new changes

**Comment by chipx86** [comment]
You'll just need to register an account on that server and, from the RBTools source tree in the correct branch, run:

```
rbt post
```

Then include the necessary info in the fields and publish. We also have more info at https://www.reviewboard.org/docs/codebase/dev/contributing-patches/

The unit tests need to demonstrate the problem. If we run just the tests without the patch, we should see that the tests fail, but with the patch, they should work.

Something to note is that Review Board/RBTools is used by at least hundreds of thousands of developers world-wide, and this means there's a wide range of configurations, encodings, operating systems, and other such things out there. Encoding-related changes can sometimes impact other users, and future changes can always regress earlier fixes, which is why we need the proof in terms of clear, reproducible, and self-explanatory unit tests. Knowing that it works for 160 developers is always good, but does nothing to guarantee it'll work for others, or keep working long-term.

**Pull request closed without merging**
