### PR TITLE
Support certifi - a better ca bundle

### PR DESCRIPTION
**Pull request by mattbillenstein**

### CODE REVIEW

**Comment by davidt** [comment]
Hi,

We don't use pull requests. Can you post this on https://reviews.reviewboard.org/ ?

Thanks!

**Comment by mattbillenstein** [comment]
Eh, last thing I need is another account on some other system I'll never use again -- feel free to pull this if you plan to think about merging it...

**Comment by johnlevin** [comment]
Hi,

I'm facing the similar issue. But for Windows rbtools. Can u please let us know how will i get the windows source code for rbtools. and what should be the changes needs to be adopted ?

**Comment by brennie** [comment]
Hi @johnlevin 

RB Tools is operating system-agnostic. This is the repository for both all of RB Tools.

**Pull request closed without merging**
