### PR TITLE
Unbreak stuff

### PR DESCRIPTION
**Pull request by heroin-moose**
Both functions call get_api() ina pre-refactoring
(see f4a2b05ee3bed7bafa730834c8c792fddcce6119) fashion that simply does
not work anymore. The proper way to fix this would be to support different
styles (password, token, etc) but for now I just want to make git hooks
usable again.

### CODE REVIEW

**Comment by davidt** [comment]
Hi. We don't use pull requests. Can you post this on https://reviews.reviewboard.org? Thanks!

**Comment by heroin-moose** [comment]
Well, I did: https://reviews.reviewboard.org/r/9198/diff/1
No replies since.

**Comment by chipx86** [comment]
Sorry for the wait on it. We've been heads-down getting Review Board 3.0 beta 2 ready for release for tomorrow, and on-boarding a new group of students for an educational mentoring program we take part in. I promise we'll get to the change once we come up for air and start on the next RBTools release.

**Comment by heroin-moose** [comment]
Okay, thanks.

**Pull request closed without merging**
